version: "3"

services:
  app:
    env_file: ./.env
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_PORT=$MYSQLDB_DOCKER_PORT
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    image: rentacar_api
    container_name: rentacar_api
    build: ./rentacar_api
    restart: on-failure
    depends_on:
      - mysqldb
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql

networks:
  services_network:
    external: true

volumes:
  db: